[2023-06-14T13:39:57.805+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:39:57.881+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:39:57.882+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:39:57.957+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-24 00:00:00+00:00
[2023-06-14T13:39:57.961+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2023-06-14T13:39:58.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-24T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpilpz4tqb']
[2023-06-14T13:39:58.043+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask create_table
[2023-06-14T13:39:58.527+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [running]> on host 770b1916921e
[2023-06-14T13:39:58.855+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-24T00:00:00+00:00'
[2023-06-14T13:39:58.860+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:39:58.940+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2023-06-14T13:39:58.947+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230424T000000, start_date=20230614T133957, end_date=20230614T133958
[2023-06-14T13:39:59.007+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task create_table (The conn_id `postgres_conn` isn't defined; 135)
[2023-06-14T13:39:59.064+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:39:59.278+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:48:48.955+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.009+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.012+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:48:49.109+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-24 00:00:00+00:00
[2023-06-14T13:48:49.118+0000] {standard_task_runner.py:57} INFO - Started process 90 to run task
[2023-06-14T13:48:49.136+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-24T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpjcdi9u4_']
[2023-06-14T13:48:49.138+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask create_table
[2023-06-14T13:48:49.282+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [running]> on host 25d93391a9f5
[2023-06-14T13:48:49.453+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-24T00:00:00+00:00'
[2023-06-14T13:48:49.454+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:48:49.482+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_connection` isn't defined
[2023-06-14T13:48:49.486+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230424T000000, start_date=20230614T134848, end_date=20230614T134849
[2023-06-14T13:48:49.499+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task create_table (The conn_id `postgres_connection` isn't defined; 90)
[2023-06-14T13:48:49.552+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:48:49.602+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:54:03.724+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:54:03.734+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:54:03.737+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:54:03.767+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-24 00:00:00+00:00
[2023-06-14T13:54:03.780+0000] {standard_task_runner.py:57} INFO - Started process 88 to run task
[2023-06-14T13:54:03.793+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-24T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpt7wwhf07']
[2023-06-14T13:54:03.799+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask create_table
[2023-06-14T13:54:04.029+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [running]> on host e981f43aaef1
[2023-06-14T13:54:04.388+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-24T00:00:00+00:00'
[2023-06-14T13:54:04.389+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:54:04.432+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:04.680+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:04.690+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:54:04.741+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230424T000000, start_date=20230614T135403, end_date=20230614T135404
[2023-06-14T13:54:04.974+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:54:05.005+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:56:50.212+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:56:50.260+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-06-14T13:56:50.263+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:56:50.394+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-24 00:00:00+00:00
[2023-06-14T13:56:50.403+0000] {standard_task_runner.py:57} INFO - Started process 87 to run task
[2023-06-14T13:56:50.420+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-24T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpg49u89jv']
[2023-06-14T13:56:50.422+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask create_table
[2023-06-14T13:56:50.760+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-24T00:00:00+00:00 [running]> on host 366197f8877d
[2023-06-14T13:56:51.202+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-24T00:00:00+00:00'
[2023-06-14T13:56:51.208+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:56:51.286+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:51.747+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:51.759+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:56:51.778+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230424T000000, start_date=20230614T135650, end_date=20230614T135651
[2023-06-14T13:56:51.876+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:56:51.938+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
