[2023-06-14T13:40:00.227+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:40:00.277+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:40:00.278+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:40:00.331+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-04 00:00:00+00:00
[2023-06-14T13:40:00.368+0000] {standard_task_runner.py:57} INFO - Started process 151 to run task
[2023-06-14T13:40:00.381+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpmb94cdav']
[2023-06-14T13:40:00.386+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask create_table
[2023-06-14T13:40:00.943+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [running]> on host 770b1916921e
[2023-06-14T13:40:01.452+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-04T00:00:00+00:00'
[2023-06-14T13:40:01.464+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:40:01.515+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2023-06-14T13:40:01.527+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230504T000000, start_date=20230614T134000, end_date=20230614T134001
[2023-06-14T13:40:01.558+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 17 for task create_table (The conn_id `postgres_conn` isn't defined; 151)
[2023-06-14T13:40:01.618+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:40:01.686+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:48:49.870+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.903+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.904+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:48:49.930+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-04 00:00:00+00:00
[2023-06-14T13:48:49.944+0000] {standard_task_runner.py:57} INFO - Started process 99 to run task
[2023-06-14T13:48:49.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpffuxnf4g']
[2023-06-14T13:48:49.952+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask create_table
[2023-06-14T13:48:50.080+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [running]> on host 25d93391a9f5
[2023-06-14T13:48:50.198+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-04T00:00:00+00:00'
[2023-06-14T13:48:50.199+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:48:50.251+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_connection` isn't defined
[2023-06-14T13:48:50.255+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230504T000000, start_date=20230614T134849, end_date=20230614T134850
[2023-06-14T13:48:50.271+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 17 for task create_table (The conn_id `postgres_connection` isn't defined; 99)
[2023-06-14T13:48:50.330+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:48:50.350+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:54:06.469+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:54:06.494+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:54:06.495+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:54:06.551+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-04 00:00:00+00:00
[2023-06-14T13:54:06.566+0000] {standard_task_runner.py:57} INFO - Started process 111 to run task
[2023-06-14T13:54:06.620+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpo78z5yqr']
[2023-06-14T13:54:06.629+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask create_table
[2023-06-14T13:54:06.903+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [running]> on host e981f43aaef1
[2023-06-14T13:54:07.167+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-04T00:00:00+00:00'
[2023-06-14T13:54:07.169+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:54:07.205+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:07.443+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:07.456+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:54:07.478+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230504T000000, start_date=20230614T135406, end_date=20230614T135407
[2023-06-14T13:54:07.569+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:54:07.662+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:56:52.573+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:56:52.659+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-14T13:56:52.662+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:56:52.809+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-04 00:00:00+00:00
[2023-06-14T13:56:52.815+0000] {standard_task_runner.py:57} INFO - Started process 105 to run task
[2023-06-14T13:56:52.841+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpfn06e7fu']
[2023-06-14T13:56:52.844+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask create_table
[2023-06-14T13:56:53.051+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-05-04T00:00:00+00:00 [running]> on host 366197f8877d
[2023-06-14T13:56:53.320+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-04T00:00:00+00:00'
[2023-06-14T13:56:53.328+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:56:53.354+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:53.532+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:53.549+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:56:53.572+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230504T000000, start_date=20230614T135652, end_date=20230614T135653
[2023-06-14T13:56:53.620+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:56:53.676+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
