[2023-06-14T13:39:58.711+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:39:58.810+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:39:58.811+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:39:58.951+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-27 00:00:00+00:00
[2023-06-14T13:39:58.987+0000] {standard_task_runner.py:57} INFO - Started process 139 to run task
[2023-06-14T13:39:59.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-27T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpigo246in']
[2023-06-14T13:39:59.038+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask create_table
[2023-06-14T13:39:59.352+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [running]> on host 770b1916921e
[2023-06-14T13:39:59.645+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-27T00:00:00+00:00'
[2023-06-14T13:39:59.656+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:39:59.834+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2023-06-14T13:39:59.901+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230427T000000, start_date=20230614T133958, end_date=20230614T133959
[2023-06-14T13:40:00.061+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task create_table (The conn_id `postgres_conn` isn't defined; 139)
[2023-06-14T13:40:00.172+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:40:00.224+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:48:49.345+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.395+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.398+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:48:49.434+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-27 00:00:00+00:00
[2023-06-14T13:48:49.457+0000] {standard_task_runner.py:57} INFO - Started process 93 to run task
[2023-06-14T13:48:49.472+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-27T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpmb4co24u']
[2023-06-14T13:48:49.474+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_table
[2023-06-14T13:48:49.617+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [running]> on host 25d93391a9f5
[2023-06-14T13:48:49.808+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-27T00:00:00+00:00'
[2023-06-14T13:48:49.811+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:48:49.852+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_connection` isn't defined
[2023-06-14T13:48:49.857+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230427T000000, start_date=20230614T134849, end_date=20230614T134849
[2023-06-14T13:48:49.869+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task create_table (The conn_id `postgres_connection` isn't defined; 93)
[2023-06-14T13:48:49.929+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:48:49.974+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:54:04.740+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:54:04.777+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:54:04.785+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:54:04.855+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-27 00:00:00+00:00
[2023-06-14T13:54:04.870+0000] {standard_task_runner.py:57} INFO - Started process 98 to run task
[2023-06-14T13:54:04.953+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-27T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpfut6rz1b']
[2023-06-14T13:54:04.960+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask create_table
[2023-06-14T13:54:05.131+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [running]> on host e981f43aaef1
[2023-06-14T13:54:05.452+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-27T00:00:00+00:00'
[2023-06-14T13:54:05.454+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:54:05.484+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:05.822+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:05.832+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:54:05.878+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230427T000000, start_date=20230614T135404, end_date=20230614T135405
[2023-06-14T13:54:06.030+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:54:06.088+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:56:51.272+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:56:51.326+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [queued]>
[2023-06-14T13:56:51.330+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:56:51.460+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-27 00:00:00+00:00
[2023-06-14T13:56:51.467+0000] {standard_task_runner.py:57} INFO - Started process 95 to run task
[2023-06-14T13:56:51.563+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-27T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmp4zl3fdhe']
[2023-06-14T13:56:51.575+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_table
[2023-06-14T13:56:51.755+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-27T00:00:00+00:00 [running]> on host 366197f8877d
[2023-06-14T13:56:52.301+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-27T00:00:00+00:00'
[2023-06-14T13:56:52.312+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:56:52.348+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:52.713+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:52.732+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:56:52.766+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230427T000000, start_date=20230614T135651, end_date=20230614T135652
[2023-06-14T13:56:52.888+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:56:52.951+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
