[2023-06-14T13:39:58.654+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:39:58.706+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:39:58.709+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:39:58.868+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-26 00:00:00+00:00
[2023-06-14T13:39:58.895+0000] {standard_task_runner.py:57} INFO - Started process 138 to run task
[2023-06-14T13:39:58.946+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-26T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpoil72ngb']
[2023-06-14T13:39:58.952+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_table
[2023-06-14T13:39:59.200+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [running]> on host 770b1916921e
[2023-06-14T13:39:59.473+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-26T00:00:00+00:00'
[2023-06-14T13:39:59.476+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:39:59.701+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2023-06-14T13:39:59.719+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230426T000000, start_date=20230614T133958, end_date=20230614T133959
[2023-06-14T13:39:59.806+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task create_table (The conn_id `postgres_conn` isn't defined; 138)
[2023-06-14T13:40:00.037+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:40:00.208+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:48:49.171+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.201+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:48:49.203+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:48:49.246+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-26 00:00:00+00:00
[2023-06-14T13:48:49.261+0000] {standard_task_runner.py:57} INFO - Started process 92 to run task
[2023-06-14T13:48:49.270+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-26T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmp1tgrdla4']
[2023-06-14T13:48:49.272+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask create_table
[2023-06-14T13:48:49.451+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [running]> on host 25d93391a9f5
[2023-06-14T13:48:49.697+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-26T00:00:00+00:00'
[2023-06-14T13:48:49.700+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:48:49.743+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_connection` isn't defined
[2023-06-14T13:48:49.750+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_table, execution_date=20230426T000000, start_date=20230614T134849, end_date=20230614T134849
[2023-06-14T13:48:49.792+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task create_table (The conn_id `postgres_connection` isn't defined; 92)
[2023-06-14T13:48:49.864+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:48:49.901+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:54:04.446+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:54:04.493+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:54:04.500+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:54:04.568+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-26 00:00:00+00:00
[2023-06-14T13:54:04.630+0000] {standard_task_runner.py:57} INFO - Started process 96 to run task
[2023-06-14T13:54:04.677+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-26T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpxh47kx51']
[2023-06-14T13:54:04.706+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_table
[2023-06-14T13:54:04.953+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [running]> on host e981f43aaef1
[2023-06-14T13:54:05.297+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-26T00:00:00+00:00'
[2023-06-14T13:54:05.301+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:54:05.343+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:05.782+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:54:05.791+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:54:05.811+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230426T000000, start_date=20230614T135404, end_date=20230614T135405
[2023-06-14T13:54:06.004+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:54:06.084+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-06-14T13:56:50.676+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:56:50.710+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-06-14T13:56:50.713+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-14T13:56:50.865+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-26 00:00:00+00:00
[2023-06-14T13:56:50.873+0000] {standard_task_runner.py:57} INFO - Started process 91 to run task
[2023-06-14T13:56:50.889+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2023-04-26T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmp_odvc6hl']
[2023-06-14T13:56:50.899+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask create_table
[2023-06-14T13:56:51.207+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2023-04-26T00:00:00+00:00 [running]> on host 366197f8877d
[2023-06-14T13:56:51.582+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-26T00:00:00+00:00'
[2023-06-14T13:56:51.583+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);
[2023-06-14T13:56:51.614+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:52.224+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-06-14T13:56:52.270+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sample_table (
    name VARCHAR(50),
    age INTEGER,
    email VARCHAR(100)
);, parameters: None
[2023-06-14T13:56:52.328+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20230426T000000, start_date=20230614T135650, end_date=20230614T135652
[2023-06-14T13:56:52.518+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:56:52.570+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
